/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufabc.tracking2u.telas;

/**
 *
 * @author tuliocarreira
 */
public class telaPrincipal extends javax.swing.JFrame {

	/**
	 * Creates new form telaPrincipal
	 */
	public telaPrincipal() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuTarefas = new javax.swing.JMenu();
        menuTarefaCadastrar = new javax.swing.JMenuItem();
        menuTarefaListar = new javax.swing.JMenuItem();
        menuColaboradores = new javax.swing.JMenu();
        menuColaboradorCadastrar = new javax.swing.JMenuItem();
        menuColaboradorListar = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tracking 2U");

        menuTarefas.setText("Tarefas");

        menuTarefaCadastrar.setText("Cadastrar");
        menuTarefaCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTarefaCadastrarActionPerformed(evt);
            }
        });
        menuTarefas.add(menuTarefaCadastrar);

        menuTarefaListar.setText("Listar");
        menuTarefaListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTarefaListarActionPerformed(evt);
            }
        });
        menuTarefas.add(menuTarefaListar);

        jMenuBar1.add(menuTarefas);

        menuColaboradores.setText("Colaboradores");

        menuColaboradorCadastrar.setText("Cadastrar");
        menuColaboradorCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuColaboradorCadastrarActionPerformed(evt);
            }
        });
        menuColaboradores.add(menuColaboradorCadastrar);

        menuColaboradorListar.setText("Listar");
        menuColaboradorListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuColaboradorListarActionPerformed(evt);
            }
        });
        menuColaboradores.add(menuColaboradorListar);

        jMenuBar1.add(menuColaboradores);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 771, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTarefaListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTarefaListarActionPerformed
        // TODO add your handling code here:
        this.setEnabled(false);
        new telaListaTarefas().setVisible(true);
    }//GEN-LAST:event_menuTarefaListarActionPerformed

    private void menuColaboradorCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuColaboradorCadastrarActionPerformed
        // TODO add your handling code here:
          this.setEnabled(false);
	new telaCadastroColaborador().setVisible(true);
    }//GEN-LAST:event_menuColaboradorCadastrarActionPerformed

    private void menuTarefaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTarefaCadastrarActionPerformed
        // TODO add your handling code here:
        	this.setEnabled(false);
		new telaCadastroTarefa(this).setVisible(true);
    }//GEN-LAST:event_menuTarefaCadastrarActionPerformed

    private void menuColaboradorListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuColaboradorListarActionPerformed
        // TODO add your handling code here:
         this.setEnabled(false);
	new telaListaColaboradores().setVisible(true);
    }//GEN-LAST:event_menuColaboradorListarActionPerformed
	

	
	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new telaPrincipal().setVisible(true);

			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuColaboradorCadastrar;
    private javax.swing.JMenuItem menuColaboradorListar;
    private javax.swing.JMenu menuColaboradores;
    private javax.swing.JMenuItem menuTarefaCadastrar;
    private javax.swing.JMenuItem menuTarefaListar;
    private javax.swing.JMenu menuTarefas;
    // End of variables declaration//GEN-END:variables
}
