/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufabc.tracking2u.telas;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import br.edu.ufabc.tracking2u.entity.Colaborador;
import br.edu.ufabc.tracking2u.persistence.PersistenceManager;
import br.edu.ufabc.tracking2u.persistence.PersistenceManagerFactory;
import br.edu.ufabc.tracking2u.ui.UIHandler;
import br.edu.ufabc.tracking2u.ui.UIHandlerImpl;

/**
 *
 * @author tuliocarreira
 */
public class telaListaColaboradores extends javax.swing.JFrame {
	private UIHandler uihandler = new UIHandlerImpl();
	private final PersistenceManager manager = PersistenceManagerFactory.buildPersistenceManager();
	telaLogin telaAnteriorLogin;
	telaPrincipal telaAnteriorPrincipal;

	/**
	 * Creates new form telaListaColaboradores
	 */
	public telaListaColaboradores() {
		this.initComponents();
		this.carregaListaColaboradores();
	}

	public telaListaColaboradores(telaPrincipal telaAnterior) {
		this();
		this.telaAnteriorPrincipal = telaAnterior;
	}

	public telaListaColaboradores(telaLogin telaAnterior) {
		this();
		this.telaAnteriorLogin = telaAnterior;
	}

	public void carregaListaColaboradores() {
		List<? super Colaborador> listaColaboradores = new ArrayList<Colaborador>();
		try {
			listaColaboradores = this.manager.list(Colaborador.class);
		} catch (IOException ex) {
			Logger.getLogger(telaListaColaboradores.class.getName()).log(Level.SEVERE, null, ex);
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(telaListaColaboradores.class.getName()).log(Level.SEVERE, null, ex);
		}
		DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
		modelo.addColumn("ID");
		modelo.addColumn("Nome");
		modelo.addColumn("Papel");

		if (listaColaboradores.isEmpty()) {
			modelo.addRow(new String[] { "Sem dados", null, null });
		}
		for (int i = 0; i < listaColaboradores.size(); i++) {
			Colaborador c = (Colaborador) listaColaboradores.get(i);
			modelo.addRow(new String[] { c.getId() + "", c.getNome(), c.getPapel() + "" });
		}
		this.tableColaboradores.setModel(modelo);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableColaboradores = new javax.swing.JTable();
        buttonCancelaListaColaboradores = new javax.swing.JButton();
        buttonEditarColaborador = new javax.swing.JButton();
        buttonCriarColaborador = new javax.swing.JButton();
        buttonExcluirColaborador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Colaboradores");

        tableColaboradores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Colaborador", "Permissões"
            }
        ));
        jScrollPane1.setViewportView(tableColaboradores);

        buttonCancelaListaColaboradores.setText("Voltar");
        buttonCancelaListaColaboradores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelaListaColaboradoresActionPerformed(evt);
            }
        });

        buttonEditarColaborador.setText("Editar");
        buttonEditarColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarColaboradorActionPerformed(evt);
            }
        });

        buttonCriarColaborador.setText("Criar");
        buttonCriarColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCriarColaboradorActionPerformed(evt);
            }
        });

        buttonExcluirColaborador.setText("Excluir");
        buttonExcluirColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExcluirColaboradorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCriarColaborador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonEditarColaborador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonExcluirColaborador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCancelaListaColaboradores)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelaListaColaboradores)
                    .addComponent(buttonEditarColaborador)
                    .addComponent(buttonCriarColaborador)
                    .addComponent(buttonExcluirColaborador))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void buttonExcluirColaboradorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonExcluirColaboradorActionPerformed
		// TODO add your handling code here:
		try {
			int linha = this.tableColaboradores.getSelectedRow();
			Colaborador c = this.manager.find(Long.valueOf(linha + 1), Colaborador.class);
			this.manager.delete(c);
			carregaListaColaboradores();

		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "Selecione um colaborador");
		}
	}// GEN-LAST:event_buttonExcluirColaboradorActionPerformed

	private void buttonCriarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonCriarColaboradorActionPerformed
		// TODO add your handling code here:
		this.setEnabled(false);
		telaCadastroColaborador tela = new telaCadastroColaborador(this);
		tela.setVisible(true);
		tela.setLocationRelativeTo(null); // *** this will center your app ***
	}

	private void buttonEditarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonEditarColaboradorActionPerformed
		// TODO add your handling code here:
		try {
			int linha = this.tableColaboradores.getSelectedRow();
			Colaborador c = this.manager.find(Long.valueOf(linha + 1), Colaborador.class);
			this.setEnabled(false);
			telaCadastroColaborador tela = new telaCadastroColaborador(this, c);
			tela.setVisible(true);
			tela.setLocationRelativeTo(null);

		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "Selecione um colaborador");
		}

	}// GEN-LAST:event_buttonEditarColaboradorActionPerformed

	private void buttonCancelaListaColaboradoresActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonCancelaListaColaboradoresActionPerformed
		// TODO add your handling code here:
		this.dispose();

	}// GEN-LAST:event_buttonCancelaListaColaboradoresActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(telaListaColaboradores.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(telaListaColaboradores.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(telaListaColaboradores.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(telaListaColaboradores.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new telaListaColaboradores().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelaListaColaboradores;
    private javax.swing.JButton buttonCriarColaborador;
    private javax.swing.JButton buttonEditarColaborador;
    private javax.swing.JButton buttonExcluirColaborador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableColaboradores;
    // End of variables declaration//GEN-END:variables
}
