/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufabc.tracking2u.telas;

import javax.swing.DefaultComboBoxModel;

import br.edu.ufabc.tracking2u.entity.Colaborador;
import br.edu.ufabc.tracking2u.entity.Papel;
import br.edu.ufabc.tracking2u.entity.StatusTarefa;
import br.edu.ufabc.tracking2u.entity.Tarefa;
import br.edu.ufabc.tracking2u.ui.UIHandler;
import br.edu.ufabc.tracking2u.ui.UIHandlerImpl;
import javax.swing.JOptionPane;

/**
 *
 * @author tuliocarreira
 */
public class telaAlteraStatus extends javax.swing.JFrame {
	UIHandler uihandler = new UIHandlerImpl();

	telaPrincipal telaAnterior;
	Colaborador colaborador;
	Tarefa tarefa;

	/**
	 * Creates new form telaAlteraStatus
	 */
	public telaAlteraStatus() {
		initComponents();
		carregaStatus(colaborador);
	}

	public telaAlteraStatus(telaPrincipal telaAnterior, Colaborador colaborador, Tarefa tarefa) {
		initComponents();
		this.telaAnterior = telaAnterior;
		this.colaborador = colaborador;
		this.tarefa = tarefa;
		textTarefa.setText(tarefa.getNome());
		textTarefa.setEditable(false);
		textStatusAtual.setText(tarefa.getStatus().getNome());
		textStatusAtual.setEditable(false);
		carregaStatus(colaborador);
	}

	public void carregaStatus(Colaborador colaborador) {
		DefaultComboBoxModel model = new DefaultComboBoxModel();
		if (colaborador.getPapel().equals(Papel.GERENTE_PROJETO)) {
			model.addElement(StatusTarefa.AGUARDANDO_ANALISE);
			model.addElement(StatusTarefa.DESCARTADA);
		}
		if (colaborador.getPapel().equals(Papel.ANALISTA_SISTEMA)) {
			model.addElement(StatusTarefa.EM_ANALISE);
			model.addElement(StatusTarefa.AGUARDANDO_DESENVOLVIMENTO);
		}

		if (colaborador.getPapel().equals(Papel.DESENVOLVEDOR)) {
			model.addElement(StatusTarefa.AGUARDANDO_TESTE);
			model.addElement(StatusTarefa.EM_DESENVOLVIMENTO);
		}

		if (colaborador.getPapel().equals(Papel.ANALISTA_TESTE)) {
			model.addElement(StatusTarefa.EM_TESTE);
			model.addElement(StatusTarefa.AGUARDANDO_VALIDACAO);
		}

		if (colaborador.getPapel().equals(Papel.CLIENTE)) {
			model.addElement(StatusTarefa.EM_APROVACAO);
			model.addElement(StatusTarefa.APROVADA);
			model.addElement(StatusTarefa.DESCARTADA);
		}

		comboboxStatus.setModel(model);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		buttonSalvar = new javax.swing.JButton();
		buttonCancelar = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		comboboxStatus = new javax.swing.JComboBox<>();
		textTarefa = new javax.swing.JTextField();
		textStatusAtual = new javax.swing.JTextField();

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Alterar Status");

		buttonSalvar.setText("Salvar");
		buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonSalvarActionPerformed(evt);
			}
		});

		buttonCancelar.setText("Cancelar");
		buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonCancelarActionPerformed(evt);
			}
		});

		jLabel1.setText("Tarefa");

		jLabel2.setText("Status atual");

		jLabel3.setText("Novo status ");

		comboboxStatus.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout
						.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE).addGroup(layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(7, 7, 7).addComponent(jLabel1))
								.addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup()
														.addGap(7, 7, 7).addComponent(jLabel3))
												.addGroup(layout.createSequentialGroup().addGap(5, 5, 5)
														.addComponent(jLabel2))
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
																false)
														.addComponent(comboboxStatus,
																javax.swing.GroupLayout.Alignment.LEADING, 0, 168,
																Short.MAX_VALUE)
														.addComponent(textStatusAtual,
																javax.swing.GroupLayout.Alignment.LEADING)))
										.addComponent(textTarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 168,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addGap(24, 24, 24).addComponent(buttonSalvar)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(buttonCancelar).addContainerGap(48, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGap(24, 24, 24)
						.addComponent(jLabel1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(textTarefa, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(27, 27, 27).addComponent(jLabel2)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(textStatusAtual, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(14, 14, 14).addComponent(jLabel3).addGap(18, 18, 18)
						.addComponent(comboboxStatus, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(buttonSalvar).addComponent(buttonCancelar))
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonCancelarActionPerformed
		// TODO add your handling code here:
		this.dispose();
		this.telaAnterior.setEnabled(true);
	}// GEN-LAST:event_buttonCancelarActionPerformed

	private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonSalvarActionPerformed
		// TODO add your handling code here:
		// como passar o colaborador atual?
		StatusTarefa status = (StatusTarefa) comboboxStatus.getSelectedItem();
		this.uihandler.manageTarefa(this.tarefa.getNome(), this.tarefa.getDescricao(), this.tarefa.getDataPrometida(),
				this.colaborador, this.tarefa, status);
		this.dispose();
		telaAnterior.carregaListaTarefas(colaborador);
		telaAnterior.setEnabled(true);
	}// GEN-LAST:event_buttonSalvarActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(telaAlteraStatus.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(telaAlteraStatus.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(telaAlteraStatus.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(telaAlteraStatus.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new telaAlteraStatus().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton buttonCancelar;
	private javax.swing.JButton buttonSalvar;
	private javax.swing.JComboBox<String> comboboxStatus;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField textStatusAtual;
	private javax.swing.JTextField textTarefa;
	// End of variables declaration//GEN-END:variables
}
