/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufabc.tracking2u.telas;

import javax.swing.JOptionPane;

import br.edu.ufabc.tracking2u.entity.Colaborador;
import br.edu.ufabc.tracking2u.entity.Papel;
import br.edu.ufabc.tracking2u.persistence.PersistenceManager;
import br.edu.ufabc.tracking2u.persistence.PersistenceManagerFactory;
import br.edu.ufabc.tracking2u.ui.UIHandler;
import br.edu.ufabc.tracking2u.ui.UIHandlerImpl;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author tuliocarreira
 */
public class telaCadastroColaborador extends javax.swing.JFrame {
	UIHandler uihandler = new UIHandlerImpl();
	telaListaColaboradores telaAnteriorLista;
	telaPrincipal telaAnteriorPrincipal;
	Colaborador colaborador;
	private final PersistenceManager manager = PersistenceManagerFactory.buildPersistenceManager();

	/**
	 * Creates new form telaCadastroColaborador
	 */
	public telaCadastroColaborador() {
		initComponents();
		carregaPermissoes();
	}

	public telaCadastroColaborador(telaPrincipal telaAnterior) {
		this();
		this.telaAnteriorPrincipal = telaAnterior;

	}

	public telaCadastroColaborador(telaListaColaboradores telaAnterior) {
		this();
		this.telaAnteriorLista = telaAnterior;

	}

	public telaCadastroColaborador(telaListaColaboradores telaLista, Colaborador c) {
		this();
		this.telaAnteriorLista = telaLista;
		this.colaborador = c;
		textNome.setText(c.getNome() + "");
		textSenha.setText(c.getSenha() + "");
		comboboxPapel.setSelectedItem(c.getPapel());
	}

	public void carregaPermissoes() {
		DefaultComboBoxModel model = new DefaultComboBoxModel();
		model.addElement("");
		model.addElement(Papel.CLIENTE);
		model.addElement(Papel.ANALISTA_TESTE);
		model.addElement(Papel.DESENVOLVEDOR);
		model.addElement(Papel.ANALISTA_SISTEMA);
		model.addElement(Papel.GERENTE_PROJETO);
		comboboxPapel.setModel(model);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        buttonSalvarColaborador = new javax.swing.JButton();
        buttonCancelarColaborador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        textSenha = new javax.swing.JPasswordField();
        comboboxPapel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Colaborador");

        buttonSalvarColaborador.setText("Salvar");
        buttonSalvarColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarColaboradorActionPerformed(evt);
            }
        });

        buttonCancelarColaborador.setText("Cancelar");
        buttonCancelarColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarColaboradorActionPerformed(evt);
            }
        });

        jLabel1.setText("Usuário");

        jLabel2.setText("Senha");

        jLabel3.setText("Permissão");

        comboboxPapel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textNome, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(comboboxPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonSalvarColaborador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCancelarColaborador)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboboxPapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSalvarColaborador)
                    .addComponent(buttonCancelarColaborador))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void buttonSalvarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonSalvarColaboradorActionPerformed
		String login = textNome.getText();
		if (login.isEmpty() || textSenha.getPassword().length == 0 || comboboxPapel.getSelectedItem() == "") {
			JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
		} else {
			char[] senha = textSenha.getPassword();
			Papel papel = (Papel) comboboxPapel.getSelectedItem();
			uihandler.manageColaborador(login, senha, papel, this.colaborador);
			this.dispose();
			telaAnteriorLista.carregaListaColaboradores();
			telaAnteriorLista.setEnabled(true);
		}

	}

	private void buttonCancelarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonCancelarColaboradorActionPerformed
		this.dispose();
		if(telaAnteriorLista != null){
			telaAnteriorLista.setEnabled(true);
		}
		else if(telaAnteriorPrincipal != null){
			telaAnteriorPrincipal.setEnabled(true);
		}
	
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(telaCadastroColaborador.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(telaCadastroColaborador.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(telaCadastroColaborador.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(telaCadastroColaborador.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new telaCadastroColaborador().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelarColaborador;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton buttonSalvarColaborador;
    private javax.swing.JComboBox<String> comboboxPapel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textNome;
    private javax.swing.JPasswordField textSenha;
    // End of variables declaration//GEN-END:variables
}
