/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufabc.tracking2u.telas;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import br.edu.ufabc.tracking2u.entity.Tarefa;
import br.edu.ufabc.tracking2u.persistence.PersistenceManager;
import br.edu.ufabc.tracking2u.persistence.PersistenceManagerFactory;

/**
 *
 * @author tuliocarreira
 */
public class telaPrincipal extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	private final PersistenceManager manager = PersistenceManagerFactory.buildPersistenceManager();

	/**
	 * Creates new form telaPrincipal
	 */
	public telaPrincipal() {
		this.initComponents();
		try {
			this.carregaListaTarefas();
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
		}
	}

	private void carregaListaTarefas() throws ClassNotFoundException {
		List<? super Tarefa> listaTarefas = new ArrayList<Tarefa>();
		try {
			listaTarefas = this.manager.list(Tarefa.class);
		} catch (IOException ex) {
			Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
		}
		DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
		modelo.addColumn("ID");
		modelo.addColumn("Nome");
		modelo.addColumn("Descrição");
		modelo.addColumn("Status");
		modelo.addColumn("Responsável");
		modelo.addColumn("Criador");
		modelo.addColumn("Data de Previsão");

		if (listaTarefas.isEmpty()) {
			modelo.addRow(new String[] { "Sem dados", null, null, null, null, null, null });
		}
		for (int i = 0; i < listaTarefas.size(); i++) {
			Tarefa t = (Tarefa) listaTarefas.get(i);
			modelo.addRow(new String[] { t.getId() + "", t.getNome(), t.getDescricao(), t.getStatus() + "",
					t.getResponsavel().getNome() + "", t.getCriador().getNome() + "", t.getDataPrometida() + "" });
		}
		this.tabelaTarefas.setModel(modelo);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		this.jMenuItem1 = new javax.swing.JMenuItem();
		this.jScrollPane1 = new javax.swing.JScrollPane();
		this.tabelaTarefas = new javax.swing.JTable();
		this.buttonCriar = new javax.swing.JButton();
		this.buttonSair = new javax.swing.JButton();
		this.buttonEditar = new javax.swing.JButton();
		this.buttonExcluir = new javax.swing.JButton();
		this.jMenuBar1 = new javax.swing.JMenuBar();
		this.menuTarefas = new javax.swing.JMenu();
		this.menuTarefaCadastrar = new javax.swing.JMenuItem();
		this.menuTarefaListar = new javax.swing.JMenuItem();
		this.menuColaboradores = new javax.swing.JMenu();
		this.menuColaboradorCadastrar = new javax.swing.JMenuItem();
		this.menuColaboradorListar = new javax.swing.JMenuItem();

		this.jMenuItem1.setText("jMenuItem1");

		this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		this.setTitle("Tracking 2U");

		this.tabelaTarefas.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { null, null, null, null },
				{ null, null, null, null }, { null, null, null, null }, { null, null, null, null } },
				new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		this.jScrollPane1.setViewportView(this.tabelaTarefas);

		this.buttonCriar.setText("Criar");
		this.buttonCriar.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				telaPrincipal.this.buttonCriarActionPerformed(evt);
			}
		});

		this.buttonSair.setText("Sair");
		this.buttonSair.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				telaPrincipal.this.buttonSairActionPerformed(evt);
			}
		});

		this.buttonEditar.setText("Editar");
		this.buttonEditar.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				telaPrincipal.this.buttonEditarActionPerformed(evt);
			}
		});

		this.buttonExcluir.setText("Excluir");
		this.buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				telaPrincipal.this.buttonExcluirActionPerformed(evt);
			}
		});

		this.menuTarefas.setText("Tarefas");

		this.menuTarefaCadastrar.setText("Cadastrar");
		this.menuTarefaCadastrar.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				telaPrincipal.this.menuTarefaCadastrarActionPerformed(evt);
			}
		});
		this.menuTarefas.add(this.menuTarefaCadastrar);

		this.menuTarefaListar.setText("Listar");
		this.menuTarefaListar.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				telaPrincipal.this.menuTarefaListarActionPerformed(evt);
			}
		});
		this.menuTarefas.add(this.menuTarefaListar);

		this.jMenuBar1.add(this.menuTarefas);

		this.menuColaboradores.setText("Colaboradores");

		this.menuColaboradorCadastrar.setText("Cadastrar");
		this.menuColaboradorCadastrar.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				telaPrincipal.this.menuColaboradorCadastrarActionPerformed(evt);
			}
		});
		this.menuColaboradores.add(this.menuColaboradorCadastrar);

		this.menuColaboradorListar.setText("Listar");
		this.menuColaboradorListar.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				telaPrincipal.this.menuColaboradorListarActionPerformed(evt);
			}
		});
		this.menuColaboradores.add(this.menuColaboradorListar);

		this.jMenuBar1.add(this.menuColaboradores);

		this.setJMenuBar(this.jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
		this.getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup()
										.addGap(18, 18,
												18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGap(6, 6, 6).addComponent(this.buttonCriar)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(this.buttonEditar)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addComponent(this.buttonExcluir)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(this.buttonSair).addGap(32, 32, 32))
						.addGroup(layout.createSequentialGroup().addComponent(this.jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
								733, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(20, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(16, 16, 16)
						.addComponent(this.jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474,
								javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(this.buttonCriar)
						.addComponent(this.buttonSair).addComponent(this.buttonEditar).addComponent(this.buttonExcluir))
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		this.pack();
	}// </editor-fold>//GEN-END:initComponents

	private void menuTarefaListarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuTarefaListarActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_menuTarefaListarActionPerformed

	private void menuColaboradorCadastrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuColaboradorCadastrarActionPerformed
		// TODO add your handling code here:
		this.setEnabled(false);
		new telaCadastroColaborador().setVisible(true);
	}// GEN-LAST:event_menuColaboradorCadastrarActionPerformed

	private void menuTarefaCadastrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuTarefaCadastrarActionPerformed
		// TODO add your handling code here:
		this.setEnabled(false);
		new telaCadastroTarefa(this).setVisible(true);
	}// GEN-LAST:event_menuTarefaCadastrarActionPerformed

	private void menuColaboradorListarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_menuColaboradorListarActionPerformed
		// TODO add your handling code here:
		this.setEnabled(false);
		new telaListaColaboradores().setVisible(true);
	}// GEN-LAST:event_menuColaboradorListarActionPerformed

	private void buttonCriarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonCriarActionPerformed
		// TODO add your handling code here:
		this.setEnabled(false);
		new telaCadastroTarefa(this).setVisible(true);
	}// GEN-LAST:event_buttonCriarActionPerformed

	private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonSairActionPerformed
		// TODO add your handling code here:
		System.exit(0);
	}// GEN-LAST:event_buttonSairActionPerformed

	private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonEditarActionPerformed
		// TODO add your handling code here:
		try {
			int linha = this.tabelaTarefas.getSelectedRow();
			Tarefa c = this.manager.find(Long.valueOf(linha), Tarefa.class);
			this.setEnabled(false);
			new telaCadastroTarefa(this, c).setVisible(true);

		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "Selecione uma tarefa");
		} // GEN-LAST:event_buttonEditarActionPerformed
	}

	private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonExcluirActionPerformed
		// TODO add your handling code here:
		try {
			int linha = this.tabelaTarefas.getSelectedRow();
			Tarefa c = this.manager.find(Long.valueOf(linha), Tarefa.class);
			this.manager.delete(c);
			JOptionPane.showMessageDialog(this, "Tarefa excluída com sucesso!");

		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "Selecione uma tarefa");
		} // GEN-LAST:event_buttonExcluirActionPerformed
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new telaPrincipal().setVisible(true);

			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton buttonCriar;
	private javax.swing.JButton buttonEditar;
	private javax.swing.JButton buttonExcluir;
	private javax.swing.JButton buttonSair;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JMenuItem menuColaboradorCadastrar;
	private javax.swing.JMenuItem menuColaboradorListar;
	private javax.swing.JMenu menuColaboradores;
	private javax.swing.JMenuItem menuTarefaCadastrar;
	private javax.swing.JMenuItem menuTarefaListar;
	private javax.swing.JMenu menuTarefas;
	private javax.swing.JTable tabelaTarefas;
	// End of variables declaration//GEN-END:variables
}
