/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufabc.tracking2u.telas;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import br.edu.ufabc.tracking2u.entity.Colaborador;
import br.edu.ufabc.tracking2u.persistence.PersistenceManager;
import br.edu.ufabc.tracking2u.persistence.PersistenceManagerFactory;

/**
 *
 * @author tuliocarreira
 */
public class telaListaColaboradores extends javax.swing.JFrame {
	private final PersistenceManager manager = PersistenceManagerFactory.buildPersistenceManager();

	/**
	 * Creates new form telaListaColaboradores
	 */
	public telaListaColaboradores() {
		this.initComponents();
		this.carregaListaColaboradores();
	}

	private void carregaListaColaboradores() {
		List<? super Colaborador> listaColaboradores = new ArrayList<Colaborador>();
		try {
			listaColaboradores = this.manager.list(Colaborador.class);
		} catch (IOException ex) {
			Logger.getLogger(telaListaColaboradores.class.getName()).log(Level.SEVERE, null, ex);
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(telaListaColaboradores.class.getName()).log(Level.SEVERE, null, ex);
		}
		DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
		modelo.addColumn("ID");
		modelo.addColumn("Nome");

		if (listaColaboradores.isEmpty()) {
			modelo.addRow(new String[] { "Sem dados", null });
		}
		for (int i = 0; i < listaColaboradores.size(); i++) {
			Colaborador c = (Colaborador) listaColaboradores.get(i);
			modelo.addRow(new String[] { c.getId() + "", c.getNome() });
		}
		this.tableColaboradores.setModel(modelo);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		this.jScrollPane1 = new javax.swing.JScrollPane();
		this.tableColaboradores = new javax.swing.JTable();
		this.buttonCancelaListaColaboradores = new javax.swing.JButton();
		this.buttonEditarColaborador = new javax.swing.JButton();

		this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		this.tableColaboradores.setModel(
				new javax.swing.table.DefaultTableModel(new Object[][] { { null, null }, { null, null }, { null, null }, { null, null } },
						new String[] { "Colaborador", "Permissões" }));
		this.jScrollPane1.setViewportView(this.tableColaboradores);

		this.buttonCancelaListaColaboradores.setText("Cancelar");
		this.buttonCancelaListaColaboradores.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				telaListaColaboradores.this.buttonCancelaListaColaboradoresActionPerformed(evt);
			}
		});

		this.buttonEditarColaborador.setText("Editar");
		this.buttonEditarColaborador.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				telaListaColaboradores.this.buttonEditarColaboradorActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
		this.getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(32, 32, 32)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addComponent(this.buttonEditarColaborador)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(this.buttonCancelaListaColaboradores).addGap(31, 31, 31))
						.addGroup(layout.createSequentialGroup().addComponent(this.jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
								482, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap(40, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(17, 17, 17)
						.addComponent(this.jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE).addGap(18, 18, 18)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(this.buttonCancelaListaColaboradores).addComponent(this.buttonEditarColaborador))
				.addContainerGap()));

		this.pack();
	}// </editor-fold>//GEN-END:initComponents

	private void buttonEditarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonEditarColaboradorActionPerformed
		// TODO add your handling code here:
		try {
			int linha = this.tableColaboradores.getSelectedRow();
			Colaborador c = this.manager.find(Long.valueOf(linha), Colaborador.class);
			this.setEnabled(false);
			new telaCadastroColaborador(this, c).setVisible(true);

		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "Selecione um colaborador");
		}
	}// GEN-LAST:event_buttonEditarColaboradorActionPerformed

	private void buttonCancelaListaColaboradoresActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonCancelaListaColaboradoresActionPerformed
		// TODO add your handling code here:
		this.dispose();
	}// GEN-LAST:event_buttonCancelaListaColaboradoresActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(telaListaColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(telaListaColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(telaListaColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(telaListaColaboradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new telaListaColaboradores().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton buttonCancelaListaColaboradores;
	private javax.swing.JButton buttonEditarColaborador;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tableColaboradores;
	// End of variables declaration//GEN-END:variables
}
