/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufabc.tracking2u.telas;

import br.edu.ufabc.tracking2u.entity.Colaborador;
import br.edu.ufabc.tracking2u.entity.Pendencia;
import br.edu.ufabc.tracking2u.entity.Tarefa;
import br.edu.ufabc.tracking2u.persistence.PersistenceManager;
import br.edu.ufabc.tracking2u.persistence.PersistenceManagerFactory;
import br.edu.ufabc.tracking2u.ui.UIHandler;
import br.edu.ufabc.tracking2u.ui.UIHandlerImpl;
import javax.swing.JOptionPane;

/**
 *
 * @author tuliocarreira
 */
public class telaCadastroPendencia extends javax.swing.JFrame {
	UIHandler uihandler = new UIHandlerImpl();

	private final PersistenceManager manager = PersistenceManagerFactory.buildPersistenceManager();
	Colaborador colaborador;
	Tarefa tarefa;
	Pendencia pendencia;
	telaListaPendencias telaAnterior;

	/**
	 * Creates new form telaCadastroPendencia
	 */
	public telaCadastroPendencia() {
		initComponents();
	}

	public telaCadastroPendencia(telaListaPendencias telaAnterior, Tarefa tarefa, Colaborador colaborador) {
		this();
		this.telaAnterior = telaAnterior;
		this.tarefa = tarefa;
		this.colaborador = colaborador;
		checkboxFinalizado.setVisible(false);

	}

	public telaCadastroPendencia(telaListaPendencias telaAnterior, Pendencia pendencia) {
		this();
		this.telaAnterior = telaAnterior;
		this.pendencia = pendencia;
		checkboxFinalizado.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		checkboxFinalizado = new javax.swing.JCheckBox();
		textNome = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		textDesc = new javax.swing.JTextArea();
		buttonSalvar = new javax.swing.JButton();
		buttonCancelar = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Cadastro de Pendência");

		checkboxFinalizado.setText("Finalizada?");

		textNome.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				textNomeActionPerformed(evt);
			}
		});

		jLabel1.setText("Nome");

		jLabel2.setText("Descrição");

		textDesc.setColumns(20);
		textDesc.setRows(5);
		jScrollPane1.setViewportView(textDesc);

		buttonSalvar.setText("Salvar");
		buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonSalvarActionPerformed(evt);
			}
		});

		buttonCancelar.setText("Cancelar");
		buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonCancelarActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout
										.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(layout.createSequentialGroup().addGap(41, 41, 41)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jLabel2).addComponent(jLabel1)
																.addComponent(checkboxFinalizado)))
												.addGroup(layout.createSequentialGroup().addGap(64, 64, 64)
														.addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE,
																100, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup().addGap(65, 65, 65).addComponent(
																jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(0, 64, Short.MAX_VALUE))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup().addGap(0, 0, Short.MAX_VALUE)
												.addComponent(buttonSalvar)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(buttonCancelar)))
								.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addGap(28, 28, 28).addComponent(jLabel1)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18).addComponent(jLabel2)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(38, 38, 38).addComponent(checkboxFinalizado)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49,
										Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(buttonSalvar).addComponent(buttonCancelar))));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textNomeActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_textNomeActionPerformed

	private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonCancelarActionPerformed
		// TODO add your handling code here:
		this.dispose();
		this.telaAnterior.setEnabled(true);

	}// GEN-LAST:event_buttonCancelarActionPerformed

	private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonSalvarActionPerformed
		// TODO add your handling code here:
		String nome = this.textNome.getText();
		String desc = this.textDesc.getText();
		boolean status = false;
		status = this.checkboxFinalizado.isSelected();
		this.uihandler.managePendencia(status, nome, desc, this.colaborador.getId(), this.tarefa.getId(),
				this.pendencia);
		this.dispose();
		telaAnterior.carregaListaPendencias(this.tarefa);
		telaAnterior.setEnabled(true);
	}// GEN-LAST:event_buttonSalvarActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(telaCadastroPendencia.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(telaCadastroPendencia.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(telaCadastroPendencia.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(telaCadastroPendencia.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new telaCadastroPendencia().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton buttonCancelar;
	private javax.swing.JButton buttonSalvar;
	private javax.swing.JCheckBox checkboxFinalizado;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea textDesc;
	private javax.swing.JTextField textNome;
	// End of variables declaration//GEN-END:variables
}
