/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufabc.tracking2u.telas;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;

import br.edu.ufabc.tracking2u.entity.Pendencia;
import br.edu.ufabc.tracking2u.persistence.PersistenceManager;
import br.edu.ufabc.tracking2u.persistence.PersistenceManagerFactory;

/**
 *
 * @author tuliocarreira
 */
public class telaListaPendencias extends javax.swing.JFrame {
	private final PersistenceManager manager = PersistenceManagerFactory.buildPersistenceManager();

	/**
	 * Creates new form telaListaPendencias
	 */
	public telaListaPendencias() {
		this.initComponents();
		this.carregaListaPendencias();
	}

	private void carregaListaPendencias() {
		List<? super Pendencia> listaPendencias = new ArrayList<Pendencia>();
		try {
			listaPendencias = this.manager.list(Pendencia.class);
		} catch (IOException ex) {
			Logger.getLogger(telaListaColaboradores.class.getName()).log(Level.SEVERE, null, ex);
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(telaListaColaboradores.class.getName()).log(Level.SEVERE, null, ex);
		}
		DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
		modelo.addColumn("ID");
		modelo.addColumn("Nome");
		modelo.addColumn("Descrição");
		modelo.addColumn("Data de Finalizacão");

		if (listaPendencias.isEmpty()) {
			modelo.addRow(new String[] { "Sem dados", null, null, null });
		}
		for (int i = 0; i < listaPendencias.size(); i++) {
			Pendencia p = (Pendencia) listaPendencias.get(i);
			modelo.addRow(new String[] { p.getId() + "", p.getNome(), p.getDescricao(), p.getDataFinalizacao() + "" });
		}
		this.tablePendencias.setModel(modelo);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		this.jScrollPane1 = new javax.swing.JScrollPane();
		this.tablePendencias = new javax.swing.JTable();
		this.buttonSair = new javax.swing.JButton();

		this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		this.tablePendencias
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		this.jScrollPane1.setViewportView(this.tablePendencias);

		this.buttonSair.setText("Sair");
		this.buttonSair.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				telaListaPendencias.this.buttonSairActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
		this.getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(this.buttonSair).addComponent(this.jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addContainerGap(19, Short.MAX_VALUE)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(12, 12, 12)
								.addComponent(this.jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292,
										Short.MAX_VALUE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(this.buttonSair).addContainerGap()));

		this.pack();
	}// </editor-fold>//GEN-END:initComponents

	private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonSairActionPerformed
		// TODO add your handling code here:
		this.dispose();
	}// GEN-LAST:event_buttonSairActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(telaListaPendencias.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(telaListaPendencias.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(telaListaPendencias.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(telaListaPendencias.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new telaListaPendencias().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton buttonSair;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tablePendencias;
	// End of variables declaration//GEN-END:variables
}
