/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufabc.tracking2u.telas;

import br.edu.ufabc.tracking2u.entity.Colaborador;
import br.edu.ufabc.tracking2u.ui.UIHandler;
import br.edu.ufabc.tracking2u.ui.UIHandlerImpl;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author tuliocarreira
 */
public class telaCadastroColaborador extends javax.swing.JFrame {
        UIHandler uihandler = new UIHandlerImpl();
	telaListaColaboradores telaLista;
        telaPrincipal telaAnterior;
	Colaborador colaborador;

	/**
	 * Creates new form telaCadastroColaborador
	 */
	public telaCadastroColaborador() {
		initComponents();
	}

	public telaCadastroColaborador(telaPrincipal telaAnterior) {
		this();
		this.telaAnterior = telaAnterior;

	}

	public telaCadastroColaborador(telaListaColaboradores telaLista, Colaborador c) {
		this();
		this.telaLista = telaLista;
		this.colaborador = c;

        }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonSalvarColaborador = new javax.swing.JButton();
		buttonCancelarColaborador = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		textLogin = new javax.swing.JTextField();
		textSenha = new javax.swing.JPasswordField();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		listPapeis = new javax.swing.JList<>();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		buttonSalvarColaborador.setText("Salvar");
		buttonSalvarColaborador.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonSalvarColaboradorActionPerformed(evt);
			}
		});

		buttonCancelarColaborador.setText("Cancelar");
		buttonCancelarColaborador.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonCancelarColaboradorActionPerformed(evt);
			}
		});

		jLabel1.setText("Login");

		textLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				textLoginActionPerformed(evt);
			}
		});

		jLabel2.setText("Senha de Acesso");

		listPapeis.setModel(new javax.swing.AbstractListModel<String>() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

			public int getSize() {
				return strings.length;
			}

			public String getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(listPapeis);

		jLabel3.setText("Permissões");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(buttonSalvarColaborador).addGap(18, 18, 18)
						.addComponent(buttonCancelarColaborador).addGap(58, 58, 58))
				.addGroup(layout.createSequentialGroup().addGap(26, 26, 26)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabel1).addGroup(layout.createSequentialGroup().addGap(6, 6, 6)
												.addComponent(textLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 95,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addComponent(jLabel2).addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE,
										95, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53,
												Short.MAX_VALUE)
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(15, 15, 15))
								.addGroup(layout.createSequentialGroup().addGap(40, 40, 40).addComponent(jLabel3)
										.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup().addGap(24, 24, 24)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel1).addComponent(jLabel3))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
								.createSequentialGroup()
								.addComponent(textLogin, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(31, 31, 31).addComponent(jLabel2)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(textSenha, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(buttonSalvarColaborador).addComponent(buttonCancelarColaborador))
								.addGap(24, 24, 24))
								.addGroup(layout.createSequentialGroup()
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(84, Short.MAX_VALUE)))));

		pack();
	}// </editor-fold>

	private void buttonSalvarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
                String login = "Login teste";
		String senha = "Senha teste";
                List<Long> codigoPapeis = new ArrayList<>();
                codigoPapeis.add(1L);
		uihandler.createColaborador(login, senha, codigoPapeis);
		JOptionPane.showMessageDialog(this, "Colaborador cadastrado com sucesso");
		this.dispose();
		telaAnterior.setEnabled(true);
	}

	private void textLoginActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void buttonCancelarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
                telaAnterior.setEnabled(true);


	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(telaCadastroColaborador.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(telaCadastroColaborador.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(telaCadastroColaborador.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(telaCadastroColaborador.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new telaCadastroColaborador().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JButton buttonCancelarColaborador;
	private javax.swing.JButton buttonSalvarColaborador;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JList<String> listPapeis;
	private javax.swing.JTextField textLogin;
	private javax.swing.JPasswordField textSenha;
	// End of variables declaration
}
