/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ufabc.tracking2u.telas;

import br.edu.ufabc.tracking2u.entity.Colaborador;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;

import br.edu.ufabc.tracking2u.entity.Pendencia;
import br.edu.ufabc.tracking2u.entity.Tarefa;
import br.edu.ufabc.tracking2u.persistence.PersistenceManager;
import br.edu.ufabc.tracking2u.persistence.PersistenceManagerFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author tuliocarreira
 */
public class telaListaPendencias extends javax.swing.JFrame {
	private final PersistenceManager manager = PersistenceManagerFactory.buildPersistenceManager();
	Tarefa tarefa;
	Colaborador colaborador;
	telaCadastroTarefa telaAnterior;

	/**
	 * Creates new form telaListaPendencias
	 */

	public telaListaPendencias(telaCadastroTarefa telaAnterior, Tarefa tarefa, Colaborador colaborador) {
		this.telaAnterior = telaAnterior;
		this.tarefa = tarefa;
		this.colaborador = colaborador;
		this.initComponents();
		this.carregaListaPendencias(tarefa);
	}

	public telaListaPendencias() {
		this.initComponents();
		this.carregaListaPendencias(tarefa);
	}

	public void carregaListaPendencias(Tarefa tarefa) {
		List<? super Pendencia> listaPendencias = new ArrayList<Pendencia>();
		try {
			listaPendencias = this.manager.list(Pendencia.class);
		} catch (IOException ex) {
			Logger.getLogger(telaListaColaboradores.class.getName()).log(Level.SEVERE, null, ex);
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(telaListaColaboradores.class.getName()).log(Level.SEVERE, null, ex);
		}
		DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();
		modelo.addColumn("ID");
		modelo.addColumn("Nome");
		modelo.addColumn("Descrição");
		modelo.addColumn("Finalizada");

		if (listaPendencias.isEmpty()) {
			modelo.addRow(new String[] { "Sem dados", null, null, null });
		}
		for (int i = 0; i < listaPendencias.size(); i++) {
			Pendencia p = (Pendencia) listaPendencias.get(i);
			if (p.getTarefa().getId().equals(tarefa.getId())) {
				String finalizada = "";
				if (p.isFinalizada()) {
					finalizada = "Sim";
				} else
					finalizada = "Nao";
				modelo.addRow(new String[] { p.getId() + "", p.getNome(), p.getDescricao(), finalizada });
			}
		}
		this.tablePendencias.setModel(modelo);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tablePendencias = new javax.swing.JTable();
		buttonSair = new javax.swing.JButton();
		buttonCriar = new javax.swing.JButton();
		buttonEditar = new javax.swing.JButton();
		buttonExcluir = new javax.swing.JButton();

		jLabel1.setText("jLabel1");

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Lista de Pendencias");

		tablePendencias
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane1.setViewportView(tablePendencias);

		buttonSair.setText("Sair");
		buttonSair.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonSairActionPerformed(evt);
			}
		});

		buttonCriar.setText("Criar");
		buttonCriar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonCriarActionPerformed(evt);
			}
		});

		buttonEditar.setText("Editar");
		buttonEditar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonEditarActionPerformed(evt);
			}
		});

		buttonExcluir.setText("Excluir");
		buttonExcluir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonExcluirActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addContainerGap().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										false)
								.addGroup(layout.createSequentialGroup().addComponent(buttonCriar)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(buttonEditar)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(buttonExcluir)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(buttonSair))
								.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(20, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(12, 12, 12)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(buttonSair).addComponent(buttonCriar).addComponent(buttonEditar)
								.addComponent(buttonExcluir))
						.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonEditarActionPerformed
		// TODO add your handling code here:
		try {
			int linha = this.tablePendencias.getSelectedRow() + 1;
			Pendencia pendencia = this.manager.find(Long.valueOf(linha), Pendencia.class);
			this.setEnabled(false);
			telaCadastroPendencia tela = new telaCadastroPendencia(this, pendencia);
			tela.setVisible(true);
			tela.setLocationRelativeTo(null);

		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "Selecione uma pendencia");
		}
	}// GEN-LAST:event_buttonEditarActionPerformed

	private void buttonExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonExcluirActionPerformed
		// TODO add your handling code here:
		try {
			int linha = this.tablePendencias.getSelectedRow();
			Pendencia p = this.manager.find(Long.valueOf(linha + 1), Pendencia.class);
			this.manager.delete(p);
			JOptionPane.showMessageDialog(this, "Pendencia excluida com sucesso");
			carregaListaPendencias(this.tarefa);

		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "Selecione uma pendencia");
		}
	}// GEN-LAST:event_buttonExcluirActionPerformed

	private void buttonCriarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonCriarActionPerformed
		// TODO add your handling code here:
		this.setEnabled(false);
		telaCadastroPendencia tela = new telaCadastroPendencia(this, this.tarefa, this.colaborador);
		tela.setVisible(true);
		tela.setLocationRelativeTo(null);
	}// GEN-LAST:event_buttonCriarActionPerformed

	private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonSairActionPerformed
		// TODO add your handling code here:
		this.dispose();
		telaAnterior.setEnabled(true);
	}// GEN-LAST:event_buttonSairActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(telaListaPendencias.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(telaListaPendencias.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(telaListaPendencias.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(telaListaPendencias.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new telaListaPendencias().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton buttonCriar;
	private javax.swing.JButton buttonEditar;
	private javax.swing.JButton buttonExcluir;
	private javax.swing.JButton buttonSair;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tablePendencias;
	// End of variables declaration//GEN-END:variables
}
